### ISSUE TITLE
Standalone apk file fails to run on hardware device

### ISSUE THREAD

**Issue by colbec** [udacity/ud851-Exercises#153]
Using Android Studio, running each of the exercises produces a *.apk file as output.
When testing my coding, I am finding that while the resulting code works fine through an emulator and using my hardware device attached to the computer as a USB device (Android 6.0.1), the apk file does not behave correctly when transferred to the device and installed. The attempt to open the app results in a "Unfortunately ??? has stopped" message with no indication why this happened.

A basic concrete example would be the simple "Hello World" produced by the base code in exercise 1. With a simple change to the string message to fetch it as a resource, the pattern above appears. Fine in the emulator and as a tethered USB device but fails as an apk.

Is there a point during the course where the necessary missing components are added and the app starts to work as an apk, or is there an element missing in the code or in my installation process? How can I debug this?

**Comment by colbec** [comment]
Ok I now have access to the logcat on the device and have extracted the relevant section where it dies when launched. It appears it cannot find a major class; is there a reason why this would happen?
```
04-14 13:49:31.376  1032  1967 I ActivityManager: Start proc 13614:com.android.example.favoritetoys/u0a129 for activity com.android.example.favoritetoys/com.example.android.favoritetoys.MainActivity
04-14 13:49:31.446 13614 13614 E AndroidRuntime: FATAL EXCEPTION: main
04-14 13:49:31.446 13614 13614 E AndroidRuntime: Process: com.android.example.favoritetoys, PID: 13614
04-14 13:49:31.446 13614 13614 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.android.example.favoritetoys/com.example.android.favoritetoys.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.android.favoritetoys.MainActivity" on path: DexPathList[[zip file "/data/app/com.android.example.favoritetoys-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.example.favoritetoys-1/lib/arm, /vendor/lib, /system/lib]]
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:150)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:174)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5418)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.android.favoritetoys.MainActivity" on path: DexPathList[[zip file "/data/app/com.android.example.favoritetoys-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.example.favoritetoys-1/lib/arm, /vendor/lib, /system/lib]]
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	... 9 more
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.example.android.favoritetoys.MainActivity
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 		... 12 more
04-14 13:49:31.446 13614 13614 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
04-14 13:49:31.456  1032  2211 W ActivityManager:   Force finishing activity com.android.example.favoritetoys/com.example.android.favoritetoys.MainActivity
04-14 13:49:31.976  1032  1306 W ActivityManager: Activity pause timeout for ActivityRecord{55e7de2 u0 com.android.example.favoritetoys/com.example.android.favoritetoys.MainActivity t141 f}
```

**Comment by colbec** [comment]
As a further comment, I find that when running the application on the phone as a "connected" device, the process leaves an installed version of the app on the device when the USB is disconnected. This version works correctly when launched on the device with the device disconnected from the Studio. So it is hard to know if the apk or the install process on the device is broken.

**Comment by jwill** [comment]
That sounds like a problem with your physical hardware, that's something we can't efficiently help with.

If you are enrolled in the free course, you can ask your question in the forums here to see if someone is having the same problem with that specific device: https://discussions.udacity.com/c/standalone-courses/developing-android-apps

Searching StackOverflow with your device name might be helpful as well.
