### ISSUE TITLE
T07.03 No such column 'timestamp'

### ISSUE THREAD

**Issue by manpreetdeol** [udacity/ud851-Exercises#170]
For the exercise T07.03 GetAllTheData, it throws the below error:
Caused by: android.database.sqlite.SQLiteException: no such column: timestamp (code 1): , while compiling: SELECT * FROM waitlist ORDER BY timestamp
                                                     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
                                                     at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
                                                     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
                                                     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
                                                     at com.example.android.waitlist.MainActivity.getAllGuests(MainActivity.java:79)
                                                     at com.example.android.waitlist.MainActivity.onCreate(MainActivity.java:50)
                                                     at android.app.Activity.performCreate(Activity.java:6662)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 

This error has been reported earlier on Udacity forum but no one has bothered to resolve this issue. Can someone please look into this issue and give us an update as to why we have this error even the Solution provided. 

Udacity Forum link:
https://discussions.udacity.com/t/no-such-column-error-timestamp-exercise-and-solution-t07-03-ex-getallthedata/227402

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
