### ISSUE TITLE
Keeps crashing when i click search for the connect to internet

### ISSUE THREAD

**Issue by SunnyBe** [udacity/ud851-Exercises#213]
FATAL EXCEPTION: main
                                                                                      Process: com.example.android.datafrominternet, PID: 19570
                                                                                      android.os.NetworkOnMainThreadException
                                                                                          at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
                                                                                          at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
                                                                                          at java.net.InetAddress.getAllByNameImpl(InetAddress.java:265)
                                                                                          at java.net.InetAddress.getAllByName(InetAddress.java:228)
                                                                                          at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
                                                                                          at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
                                                                                          at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
                                                                                          at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
                                                                                          at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
                                                                                          at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
                                                                                          at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
                                                                                          at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
                                                                                          at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                                          at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                                                                                          at com.example.android.datafrominternet.utilities.NetworkUtils.getResponseFromHttpUrl(NetworkUtils.java:76)
                                                                                          at com.example.android.datafrominternet.MainActivity.makeGithubSearchQuery(MainActivity.java:64)
                                                                                          at com.example.android.datafrominternet.MainActivity.onOptionsItemSelected(MainActivity.java:82)
                                                                                          at android.app.Activity.onMenuItemSelected(Activity.java:2900)
                                                                                          at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
                                                                                          at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
                                                                                          at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                                                          at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:675)
                                                                                          at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                                          at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                                          at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                                          at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
                                                                                          at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
                                                                                          at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
                                                                                          at android.view.View.performClick(View.java:4788)
                                                                                          at android.view.View$PerformClick.run(View.java:19881)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5348)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

**Comment by Erbros** [comment]
I am having the same issue, even when trying the solution to the task.

**Comment by deepakshrma** [comment]
expected behavior 
https://github.com/udacity/ud851-Exercises/issues/41
