### ISSUE TITLE
T08.03-Solution-FinishQuizExample : App crashed while accesing data through ContentProvider

### ISSUE THREAD

**Issue by rahulsahni06** [udacity/ud851-Exercises#347]
The **QuizExample App (Solution code)** works fine while **DroidTermsExample App** is running in the background but as soon as I completely close the **DroidTermsExample App** (swipe it off from recents) and the try to run **QuizExample App (Solution code)** then it crashes giving the following errors:

> 05-05 11:31:24.419 10814-11014/com.udacity.example.quizexample E/ActivityThread: Failed to find provider info for com.example.udacity.droidtermsexample
05-05 11:31:24.439 10814-10814/com.udacity.example.quizexample E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.udacity.example.quizexample, PID: 10814
java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndex(java.lang.String)' on a null object reference
    at com.udacity.example.quizexample.MainActivity$WordFetchTask.onPostExecute(MainActivity.java:165)
    at com.udacity.example.quizexample.MainActivity$WordFetchTask.onPostExecute(MainActivity.java:136)
    at android.os.AsyncTask.finish(AsyncTask.java:695)
    at android.os.AsyncTask.-wrap1(Unknown Source:0)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6809)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

I also posted this in [forum](https://discussions.udacity.com/t/app-crashed-while-accessing-data-through-contentprovider/682105)

**Comment by srrobo92** [comment]
Did you ever figure this out?? I'm having the same problem

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
