### ISSUE TITLE
T02.06-Exercise-AddPolish: Github repositories are not getting fetched

### ISSUE THREAD

**Issue by kuldeepiitg** [udacity/ud851-Exercises#363]
I tried to run the solution on qemu with following config:

<img width="310" alt="screen shot 2018-05-28 at 12 43 35 pm" src="https://user-images.githubusercontent.com/1637382/40602039-fc1a4bc8-6274-11e8-8355-e7980e1f92c8.png">

05-28 12:32:26.581 26363-26811/com.example.android.datafrominternet I/com.example.android.datafrominternet.utilities.NetworkUtils: https://api.github.com/search/repositories?q=android&sort=stars
05-28 12:32:26.585 1384-1405/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 30101164 , only wrote 30101040
05-28 12:32:26.872 1384-1405/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
05-28 12:32:28.596 1384-1405/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 720 frames
05-28 12:32:29.795 1384-1406/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 30407129 , only wrote 30255120
05-28 12:32:31.454 1627-1671/? D/WifiNative-HAL: Failing getSupportedFeatureset because HAL isn't started
05-28 12:32:31.455 1627-1643/? E/BluetoothAdapter: Bluetooth binder is null
    
    --------- beginning of system
05-28 12:32:31.455 1627-1643/? E/BatteryStatsService: no controller energy info supplied
05-28 12:32:31.459 1627-1643/? E/KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
05-28 12:32:31.459 1627-1643/? E/KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
05-28 12:32:31.460 1627-1643/? E/BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
05-28 12:33:46.671 26363-26811/com.example.android.datafrominternet W/System.err: java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
        at java.net.InetAddress.getAllByName(InetAddress.java:752)
        at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
        at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:345)
05-28 12:33:46.672 26363-26811/com.example.android.datafrominternet W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
        at com.example.android.datafrominternet.utilities.NetworkUtils$override.getResponseFromHttpUrl(NetworkUtils.java:78)
        at com.example.android.datafrominternet.utilities.NetworkUtils$override.access$dispatch(NetworkUtils.java)
        at com.example.android.datafrominternet.utilities.NetworkUtils.getResponseFromHttpUrl(NetworkUtils.java)
        at com.example.android.datafrominternet.MainActivity$GithubQueryTask.doInBackground(MainActivity.java:121)
        at com.example.android.datafrominternet.MainActivity$GithubQueryTask.doInBackground(MainActivity.java:107)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
    Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
05-28 12:33:46.673 26363-26811/com.example.android.datafrominternet W/System.err:     at libcore.io.Posix.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
    	... 25 more
05-28 12:34:25.113 1627-1671/? I/WifiConnectivityManager: start a single scan from watchdogHandler
    scheduleWatchdogTimer
05-28 12:36:06.501 1627-1675/? D/ConnectivityService: NetworkAgentInfo [MOBILE (LTE) - 100] validation failed

Not sure what exactly is going wrong.

**Comment by johnshea** [comment]
Sorry but we are unable to troubleshoot individual errors.
