### ISSUE TITLE
T(Not 01, ?): Permission for audio not granted, audio cannot run

### ISSUE THREAD

**Issue by omkarlubal** [udacity/ud851-Exercises#384]
When i ran this app it kept giving me error toast message stating "Permission for audio not granted. Visualizer can't run.". So when i changed the line 82 from:

if (ActivityCompat.checkSelfPermission(this, Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED)

to

if (ActivityCompat.checkSelfPermission(this, Manifest.permission.RECORD_AUDIO) == PackageManager.PERMISSION_GRANTED)

It finally started but now i have this other error:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.omkar.audiovisualizer, PID: 8996
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.omkar.audiovisualizer/com.example.omkar.audiovisualizer.VisualizerActivity}: java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -3
                      at android.media.audiofx.Visualizer.<init>(Visualizer.java:218)
                      at com.example.omkar.audiovisualizer.AudioVisuals.AudioInputReader.initVisualizer(AudioInputReader.java:51)
                      at com.example.omkar.audiovisualizer.AudioVisuals.AudioInputReader.<init>(AudioInputReader.java:41)
                      at com.example.omkar.audiovisualizer.VisualizerActivity.setupPermissions(VisualizerActivity.java:91)
                      at com.example.omkar.audiovisualizer.VisualizerActivity.onCreate(VisualizerActivity.java:42)
                      at android.app.Activity.performCreate(Activity.java:6975)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by julian-gamboa-bahia** [comment]
Please, you can explain more about your system. Thanks

**Comment by omkarlubal** [comment]
@julian-gamboa-bahia I run it on my emulator Nexus 5X API 26 (Oreo 8.0). What might be the problem? Thanks for your help

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
