### ISSUE TITLE
StrictMode$AndroidBlockGuardPolicy.onNetwork

### ISSUE THREAD

**Issue by kungfux** [udacity/ud851-Exercises#52]
I got a runtime error in [Lesson02-GitHub-Repo-Search / T02.04-Solution-ConnectingToTheInternet](https://github.com/udacity/ud851-Exercises/blob/student/Lesson02-GitHub-Repo-Search/T02.04-Solution-ConnectingToTheInternet/app/src/main/java/com/example/android/datafrominternet/MainActivity.java) while pressing the Search button.

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.android.datafrominternet, PID: 3471
                  android.os.NetworkOnMainThreadException
                      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
                      at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:86)
                      at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
                      at java.net.InetAddress.getAllByName(InetAddress.java:752)
                      at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
                      at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
                      at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
                      at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
                      at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:345)
                      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
                      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
                      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                      at com.example.android.datafrominternet.utilities.NetworkUtils.getResponseFromHttpUrl(NetworkUtils.java:76)
                      at com.example.android.datafrominternet.MainActivity.makeGithubSearchQuery(MainActivity.java:68)
                      at com.example.android.datafrominternet.MainActivity.onOptionsItemSelected(MainActivity.java:85)
                      at android.app.Activity.onMenuItemSelected(Activity.java:3204)
                      at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
                      at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
                      at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                      at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:675)
                      at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                      at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                      at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                      at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
                      at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
                      at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
                      at android.view.View.performClick(View.java:5610)
                      at android.view.View$PerformClick.run(View.java:22265)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Seems following code could resolve the problem:**

`StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
StrictMode.setThreadPolicy(policy);`

**Comment by kungfux** [comment]
Seems the exception was an idea of the course itself.
